### ISSUE TITLE
Территория банд

### ISSUE THREAD

**Issue by KoRRd93** [alexpapay/GTA5_reallife#16]
Каждая банда имеет свою казну, в которую каждый час поступают средства ( Чем больше территория банды, тем больше денег поступает этой банде ) Управлять этими деньгами может только глава фракции и его заместитель ( Они сами выбирают что им делать, могут выдать зарплаты участникам, могут закупить оружие или наркотики, вообщем этот вопрос они регулируют сами ) 

Сама территория раньше выглядела так http://clip2net.com/s/3IU3rIG . 
Только находясь внутри цветной зоны начиналась территория "Гетто" и на ней можно было купить оружие или снять форму с военного ( форма с военного снималась только если убить его на цветной зоне, за цветной зоной военный при смерти просто отправлялся на базу ) Так-же бандиты могли продавать оружие только на территории гетто ( не имеет значения чья банда владеет этой территорией )

Каждые часа 3 проходил капт территории ( капт - это мероприятие где глава банды собирает на определенном квадрате территории свою банду и все как угарелые вводят команду [/capture] - Захват территории ( доступно с 7 ранга). и тот кто попадает ближе всего к пейдею забивет стрелку той банде на чьей территории он каптил. И в течении минут 15-20 банды сражаются на этой территории по окончанию времени та банда которую меньше всего убивали или же та которая держалась на маркере зоны дольше, становится владельцем этой территории. Для наглядности под постом будет видео.

Так же у банд есть своя монополия о которой становится все понятно прочитав список команд:
[/robhouse] - Ограбить дом (только в гетто,на своей территории).
[/sellzone] - Продать территорию ( доступно,только лидеру).
[/gwithdraw] - Снять с банка банды деньги ( доступно,только лидеру).
[/uninvite] - Уволить из банды ( доступно с 8 ранга).
[/invite] - Пригласить кого либо в банду ( доступно с 9 ранга).
[/giverank] - Повышение/Понижение ранга ( доступно с 7 ранга).
[/get guns] [кол-во] - Взять материалы со склада банды. ( доступно с 4 ранга).
[/warehouse] - Посмотреть количество материалов на складе.
[/gbank] [сумма] - Положить деньги в банк банды.
[/materials sell] - Продать материалы на склад мафии ( доступно с 8 ранга).
[/capture] - Захват территории ( доступно с 7 ранга).
[/unloading] - Разгрузить материалы на склад банды.
[/materials get] - Взять материалы c главного склада "Зоны 51"
[/materials put] - Поместить материалы в фуру.
[/sellgun] [ Название оружия ] [ Кол-во патронов ] [ Цена ] [ id ] - Продать оружие.
[/gunlist] - Просмотреть список оружия.
[/selldrugs] [ id ] [ кол-во ] [ цена ] - Продать наркотики.
[/usedrugs] [ кол-во ] - Употребить наркотики ( кол-во зависит от зависимости,максимально 15).
[/get drugs] - Купить наркотиков в притоне.
[/gbalance] - Посмотреть денежный счет банды.

Видео по бандам - https://www.youtube.com/watch?v=eSAlm_SSnes

**Comment by alexpapay** [comment]
Закрываю. Свел все в один пост чтобы не путаться. Просьба - фракции или отдельные игровые моменты описывайте одним тикетом. Лучше добавляя туда посты. А то я довольный запиил по прошлому посту логику банд, а оказалось - тут есть команды которых не было там (или же уровни доступа к командам).
