### ISSUE TITLE
Банды (FAQ)

### ISSUE THREAD

**Issue by KoRRd93** [alexpapay/GTA5_reallife#26]
Каждая банда имеет свою казну, в которую каждый час поступают средства ( Чем больше территория банды, тем больше денег поступает этой банде ) Управлять этими деньгами может только глава фракции и его заместитель ( Они сами выбирают что им делать, могут выдать зарплаты участникам, могут закупить оружие или наркотики, вообщем этот вопрос они регулируют сами )

1. Гетто
Гетто, это то место где находятся все банды. Чем больше у банды "квадратов", тем больше денег получает банда в казну (инфу не нашел, в поисках).
Только в границе территории гетто, банды могут покупать форму у военных, наркотики и производить оружие.

Делать оружие за границей гетто они не могут, но могут продавать наркотики.

2. Наркотики
Наркотики нужны для того, чтобы пополнять здоровье, так же для продажи.
Цена за один грамм наркотиков в притоне составляет 20 Вирт, с собой можно носить не более 150грамм.

Купить наркотик /get drugs [количество]
Накротик можно употребить командой /usedrugs [количество]
Продать наркотик /selldrugs [id] [количество] [цена]

От наркотиков максимальное HP 120 - При зависимости менее 2000
От наркотиков максимальное HP 130 - При зависимости от 2000 до 3000
От наркотиков максимальное HP 140 - При зависимости от 3000 до 4000
От наркотиков максимальное HP 150 - При зависимости от 4000 до 5000
От наркотиков максимальное HP 160 - При зависимости от 5000 и более
Так же чем больше ваша зависимость, тем больше наркотиков вы сможете съесть за раз
Ломка от нарко начинается при зависимости 3000 и более
Чем больше зависимость, тем чаще будет ломка, и тем реже будет передоз.

Зависимость пополняется с каждым разом при употреблении наркотиков.
Лечить ее могут врачи (будет в разделе для врачей)

3. Капт (захват)
Капт, осуществлять можно только с 7 ранга
Тут расскажем , как правильно каптить.
Для захвата территории предназначена команда - /capture что и в переводе с английского языка - захват.

Первый капт начинается в 05:00 по Москве. После рестарта сервера.
Промежутки между каптами 2 часа. Допустим, закаптили в 05:00, то следующий капт в 07:00.
Так же возможно война за территорию больше часа. Допустим закаптили в 15:00, терра кончилась в 16:20. Т.е. уже после PayDay, тогда терра будет не в 17:00, а в 18:00.
Напавшая банда может забрать территорию, только после 10 минут от PayDay и когда на этой территории не будет той банды на которую напали.

Сама территория раньше выглядела так http://clip2net.com/s/3IU3rIG .
Только находясь внутри цветной зоны начиналась территория "Гетто" и на ней можно было купить оружие или снять форму с военного ( форма с военного снималась только если убить его на цветной зоне, за цветной зоной военный при смерти просто отправлялся на базу ) Так-же бандиты могли продавать оружие только на территории гетто ( не имеет значения чья банда владеет этой территорией )

Каждые часа 3 проходил капт территории ( капт - это мероприятие где глава банды собирает на определенном квадрате территории свою банду и все как угарелые вводят команду [/capture] - Захват территории ( доступно с 7 ранга). и тот кто попадает ближе всего к пейдею забивет стрелку той банде на чьей территории он каптил. И в течении минут 15-20 банды сражаются на этой территории по окончанию времени та банда которую меньше всего убивали или же та которая держалась на маркере зоны дольше, становится владельцем этой территории. Для наглядности под постом будет видео.

4. Команды

Как и везде у банд так же есть команды.
Ниже приведен список команд для банд:

/f [текст] - чат семьи. 
/members - посмотреть членов организации в режиме онлайн.
/gbank [сумма] - положить на счет банды определенное кол-во денег. 
/warehouse - Количество материалов на складе. 
/robhouse - Ограбить дом. 
/switchskin - Одеть военную форму.
/carm- загрузить материалы в военную фуру.
/gbalance - посмотреть кол-во денег в банке банды.
/unloading - разгрузить материалы на общий склад банды с помощью фургона или матовоза. 
/clist - смена цвета ( выкл. цвета ).
/sellekey [ id ] [ цена ] - Продать ключ. 
/getekey - посмотреть кол-во ключей. 
/usedrugs [кол-во] - употребить наркотики.
/gunlist - показывает список доступных орудий и расходы материалов для их создания. 
/selldrugs [ид] [кол-во] [цена] - продать наркотики. 
/get drugs [кол-во] - купить наркотики(в притоне). 
/sellgun [название оружия] [партоны] [цена] [ид]- продать оружие. 
/materials get - взять общ. материалы(на складе ЛВа или ЛСс).
/materials put - положить материалы в фургон .
/get guns [кол-во] - [color=#BDB76B]взять материалы со склада банды. 
/capture - напасть на территорию вражеской банды.
/giverank [ID] [rank] - повысить / понизить человека.
/uninvite [ID] - Уволить игрока из организации.
/materials sell [id] [цена за 1 мат] - продать материалы мафии. 
/materials load- загрузить материалы со склада в фуру.
/invite [ID] - принять игрока в организацию.
/gangwithdraw - взять деньги с банка банды.
/sellzone - продать территорию.

**Comment by alexpapay** [comment]
Добавлено меню бандита. Можно делать из материалов оружие. Его можно продавать. Есть маркер где можно одеть/снять украденную/купленную форму. Форма также пропадает при смерти перса. По командам: чат по группе есть, вклад в общак есть, работа с материалами вся через меню (эргономику оттестим), принять игрока, повысить и уволить - есть.

Осталось:
- наркота (не совсем понял - сколько грамм то используется для лечения? хранить можно 150 на руках, а сколько за раз принимается и сколько продается?). И вообще можно полный алгоритм по наркоте?
- территории банд для капта (нужны координаты хотя бы пары территорий для тестов и отрисовки - писал про это в скайп);
- /members - посмотреть членов организации в режиме онлайн. В стадии разработки сразу для всех фракций.
- /materials sell [id] [цена за 1 мат] - продать материалы мафии. У мафии тоже склад свой есть? Сделаю тогда как опишите мафию.
- /gangwithdraw - взять деньги с банка банды. У кого права на это?
- /sellzone - продать территорию. Аналогично - у кого права на это?

**Comment by alexpapay** [comment]
Добавлено: снять денег с банка банды (прочел в соседнем тикете насчет прав).
- [/invite] - Пригласить кого либо в банду ( доступно с 9 ранга). - обновлен уровень доступа по правам
- [/uninvite] - Уволить из банды ( доступно с 8 ранга). Обновлен уровень доступа.
- [/giverank] - Повышение/Понижение ранга ( доступно с 7 ранга). Добавлено.
- [/get guns] [кол-во] - Взять материалы со склада банды. ( доступно с 4 ранга). Добавлено.

**Осталось:**
- [/robhouse] - Ограбить дом (только в гетто,на своей территории).
территорию. Права нашел - может только босс.
- [/materials sell] - Продать материалы на склад мафии ( доступно с 8 ранга). А тут бы прописать мафию, чтобы не болванить и не запутаться потом.

- [/capture] - Захват территории ( доступно с 7 ранга).
- [/sellzone] - Продать территорию ( доступно,только лидеру). Тут бы иметь хоть какую то территорию.

- [/selldrugs] [ id ] [ кол-во ] [ цена ] - Продать наркотики.
- [/usedrugs] [ кол-во ] - Употребить наркотики ( кол-во зависит от зависимости,максимально 15).
- [/get drugs] - Купить наркотиков в притоне. По наркотикам жду пояснений.

**Comment by alexpapay** [comment]
Сделано:

- [/sellzone] - Продать территорию ( доступно,только лидеру). Тут бы иметь хоть какую то территорию.  **НУЖЕН ТЕСТ!**

- [/robhouse] - Ограбить дом (только в гетто,на своей территории).
территорию. Как заведу дома - пропишу. Логику нашел: Итак, одним из самых грязных заработков является ограбление домов. Суть проста, очистить дом находящийся на территории вашей банды, забрать металл. Всё это производится командой /robhouse на иконке дома. Далее вам выпадает два варианта, либо человек спит( офф ), либо ограбление удалось. Награбленное вы сможете отвезти на прием металла (/GPS > Важные > Прием металла). Металл вы сможете сдать на 500 баксов.

- [/capture] - Захват территории ( доступно с 7 ранга). **НУЖЕН ТЕСТ!**

- [/materials sell] - Продать материалы на склад мафии ( доступно с 8 ранга). Как мафию пропишу - допилю функцию в меню.  **НУЖЕН ТЕСТ!**

**Осталось:**

- [/selldrugs] [ id ] [ кол-во ] [ цена ] - Продать наркотики.
- [/usedrugs] [ кол-во ] - Употребить наркотики ( кол-во зависит от зависимости,максимально 15).
- [/get drugs] - Купить наркотиков в притоне. По наркотикам жду пояснений.

- /members - посмотреть членов организации в режиме онлайн. В разработке для всех фракций.

- /clist - смена цвета ( выкл. цвета ). Что это?
- /sellekey [ id ] [ цена ] - Продать ключ. Что это?
- /getekey - посмотреть кол-во ключей. Что это?

**Comment by alexpapay** [comment]
Тикет закрываю. Все сделано. Осталось: 
- /sellekey [ id ] [ цена ] - Продать ключ. Что это?
- /getekey - посмотреть кол-во ключей. Что это?
Напишите или в скайп в личку или в вк плиз про ключи.
