### ISSUE TITLE
Зарплаты во фракциях

### ISSUE THREAD

**Issue by KoRRd93** [alexpapay/GTA5_reallife#27]
Мэрия
Секретарь - 6.000$
Адвокат - 6.000$
Охранник - 8.000$
Нач. Охраны - 10.000$
Зам. Мэра - 16.000$
Мэр - 20.000$
Адвокат помимо основной зарплаты получает зарплату за освобождение людей. Начисляется полная сумма, которую вы указали. Так же возможно два варианта начисления, смотря какой способ оплаты выберет человек.

ФБР
Стажер - 6.000$
Дежурный - 8.000$
Мл. Агент - 9.000$
Агент GNK - 10.000$
Агент СID - 11.000$
Глава GNK - 12.000$
Глава CID - 13.000$
Инспектор - 14.000$
Зам. Директора - 15.000$
Директор - 16.000$
За аресты бонус к зарплате идентичен полиции(указан ниже).

Полиция
Кадет - 5.000$
Офицер - 5.500$
Мл. Сержант - 6.000$
Сержант - 6.500$
Прапорщик - 7.000$
Старший Прапорщик - 7.500$
Младший Лейтенант - 8.000$
Лейтенант - 8.500$
Старший лейтенант - 9.000$
Капитан - 9.500$
Майор - 10.000$
Подполковник - 10.500$
Полковник - 11.000$
Шериф - 12.000$
Так же идёт бонус к зарплате за аресты. Смотря сколько у преступника было звезд. За одну звезду - 200 вирт. Пример: У преступника 3 звезды, вы сажаете, бонус к зарплате 600 вирт.

Армия
Рядовой - 3.000$
Ефрейтор - 3.500$
Мл.Сержант - 4.000$
Сержант - 4.500$
Ст.Сержант - 5.000$
Старшина - 5.500$
Прапорщик - 6.000$
Мл.Лейтенант - 6.500$
Лейтенант - 7.000$
Ст.Лейтенант - 7.500$
Капитан - 8.000$
Майор - 8.500$
Подполковник - 9.000$
Полковник - 9.500$
Генерал - 10.000$
Так же идёт бонус к зарплате за убийство бандитов на территории армии и в порту(желтая зона). За каждого бандита дается 500 вирт. И идёт бонус за доставки. В случае LVa по 250 вирт за каждую доставку(именно доставить на маркер фракции), независимо от того, сколько вы разгрузили, то есть можно прокатиться по всем ПД, СФа и ФБР и если у вас хватит груза на все эти фракции, то вы получите 1250 вирт.

МЧС
Интерн - 4.900$
Санитар - 5.400$
Мед. Брат - 5.900$
Спасатель - 6.400$
Нарколог - 6.900$
Доктор - 7.400$
Психолог - 7.900$
Хирург - 8.400$
Зам. Глав. Врача - 10.400$
Глав. Врач - 12.400$
Так же идёт бонус за вылеченных людей. Бонус зависит от установленной цены на лечение. Вам начисляется половина от суммы выплаченной больным.

Инструкторы
Зарплата по рангам (% от стоимости лицензии, Лимит за час)
Стажер - 4000 $.
Консультант - 10% и 10.000$ лимит
Экзаменатор - 11% и 10.500$ лимит
Младший инструктор - 12% и 11.000$ лимит
Инструктор - 13% и 11.500$ лимит
Координатор - 14% и 12.000$ лимит
Младший Менеджер- 15% и 13.000$ лимит
Старший Менеджер - 16% и 14.000$ лимит + 5% со всех проданных другими сотрудниками
Директор - 18% и 16.000 лимит + 8% со всех проданных другими сотрудниками
Управляющий - 20% и 19.000$ лимит + 10% со всех проданных другими сотрудниками

Мафия
1 ранг - 3.500$
2 ранг - 4.500$
3 ранг - 5.500$
4 ранг - 6.500$
5 ранг - 7.500$
6 ранг - 8.500$
7 ранг - 9.500$
8 ранг - 10.500$
9 ранг - 11.500$
10 ранг - 12.500$

Банда
Зарплата начисляется за кол-во квадратов, независимо от ранга. За один квадрат - 50 вирт. Пример: У вашей банды 100 квадратов, умножаете 50 на 100, зарплата 5000 вирт.
Зарплата попадает на банк банды, ее распределяет глава фракции.

**Comment by alexpapay** [comment]
Забыл тут отметить, что каждые 60 минут пребывания в игре - зарплата. По бандам вернусь сюда когда будет по квадратам мне структура кода понятна. И сами квадраты тоже.

**Comment by alexpapay** [comment]
Допилил начисление в банк банд зарплаты. Пока каждый час, но могу поставить как удобно. Тикет закрою, т.к. жду ответа в скайпе от вас про периодичность выплаты и все.
