### ISSUE TITLE
Оружие для фракций (Гос. фракции)

### ISSUE THREAD

**Issue by KoRRd93** [alexpapay/GTA5_reallife#29]
**1.Военные**
цвет - Army	4

Тип:
Пистолет:
Hash: -1045183535
Name: Revolver

Винтовка:
Hash: -2084633992
Name: CarbineRifle

Снайпер:
Hash: 100416529
Name: SniperRifle

Гранаты:
Hash: -37975472
Name: SmokeGrenade

Спец.средства:
Hash: 1198879012
Name: FlareGun

**2.Полиция**
цвет - LSPD	5

Пистолет:
Hash: -1045183535
Name: Revolver

Винтовка:
Hash: 1649403952
Name: CompactRifle

Обрез:
Hash: 487013001
Name: PumpShotgun

Гранаты:
Hash: -1600701090
Name: BZGas

Спец.Средства:
Hash: 1737195953
Name: Nightstick

Hash: 911657153
Name: StunGun

**2.ФБР**
цвет - LSPD	5 (или black если есть)

Пистолет:
Hash: -771403250
Name: HeavyPistol

Винтовка:
Hash: 2132975508
Name: BullpupRifle

Обрез:
Hash: 984333226
Name: HeavyShotgun

Гранаты:
Hash: -1600701090
Name: BZGas

Hash: -37975472
Name: SmokeGrenade

Спец.Средства:
Hash: 1737195953
Name: Nightstick

Hash: 911657153
Name: StunGun

Бандиты могут производить любое оружие кроме:
1. Hash: 1737195953
Name: Nightstick

2.Heavy Weapons (всего раздела)

3.Hash: 741814745
Name: StickyBomb

4.Hash: -1600701090
Name: BZGas

На сервере запрещено оружие: (Людей у кого появляется это оружие кикает с сервера)

1. Hash: 1119849093
Name: Minigun

**Comment by alexpapay** [comment]
Оружие добавил в разные меню фракций. Любое для бандитов делать не стал - дабы не размазывать базу. Сделал исключения описанные в тикете. Просьба еще дополнить тикет стоимостью и сколько патронов давать при создании. При дисконнекте оружие сохраняется. Число патронов тоже. При смерти все оружие пропадает. При спавне - появляется. Цвета прикручены.

**Comment by alexpapay** [comment]
По пути добавил проверку на наличие Минигана при смене оружия. Теперь пользователя кикает от этого.
