### ISSUE TITLE
Мэрия.

### ISSUE THREAD

**Issue by alexpapay** [alexpapay/GTA5_reallife#3]
На этом месте должен быть вход в мэрию ( Мэрия это здание где люди устраиваются на работу и получает регистрацию + тут должна находиться фракция мэрии )

![qlmj-i77xtu](https://cloud.githubusercontent.com/assets/18499853/23749254/9b0ba64e-04c7-11e7-9e02-4f198267a452.jpg)

По работам в мэрии: там должны быть такие работы ( Таксист, водитель автобуса, грузчик, механик ) Это основные, потом еще дополним.

**Comment by alexpapay** [comment]
Вопросов несколько:
- Телефон. Как его реализуем? Я видел у амазов на рп сервере отдельное меню, откуда можно даже смс слать. И они даже хранятся. Такое сделать в прицнипе можно. Не сильно быстро, но можно. Также ессно как разберусь с голосом - можно будет сделать мобильные звонки;
- Оружие в данной фракции откуда берется? У них тоже склад с матами на которые вояки возят маты и из них делается оружие? Или как?
- Про казну, налоги итд - надо отдельный тикет про экономику игры. Тогда интегрирую все функции. 
- Ну и инт ждемс по размещению там фракции полноценно.

**Comment by KoRRd93** [comment]
> 1. Телефон. Как его реализуем? Я видел у амазов на рп сервере отдельное меню, откуда можно даже смс слать. И они даже хранятся. Такое сделать в прицнипе можно. Не сильно быстро, но можно. Также ессно как разберусь с голосом - можно будет сделать мобильные звонки;

1. Если есть такая возможность можно и так как у них, если есть трудности то для начала можно поместить в одно из меню (1,2,3,4.). Сейчас самая важная функция там смс, для общения в ПМ.

> 2. Оружие в данной фракции откуда берется? У них тоже склад с матами на которые вояки возят маты и из них делается оружие? Или как?

2. У них нет оружия, только дубинка ментовская и тазер (Для этого БП не нужны) Просто ставим типо оружейной где могут брать эту херню они.

> 3. Про казну, налоги итд - надо отдельный тикет про экономику игры. Тогда интегрирую все функции.

3. Опишу ниже

> 4. Ну и инт ждемс по размещению там фракции полноценно.

4. Пытался разобраться, скинул тебе ту прогу типо Эдитора на англ.яз. Ты смотрел ее? (Алексею)
А так в душе не чаю как копировать или создавать норм инт :)

**Comment by KoRRd93** [comment]
Наткнулся на очень хорошую статью по вопросам налогов:

> Опыт в индустрии самп РП имею большой, играю с 2010 года. Налог он берётся как и в реальной жизни, т. е. 13 процентов от суммы дохода за час. Чем больше зарабатываешь, тем больше платишь, всё просто... но это только если ты работаешь на государство и платит тебе государство. 
> Работы которые ты берёшь в мэрии они все государственные, такая же тема с Гос. Структурами: Армии, МЧС, ПД, ФБР. Ашники платят налог с 6000 в час, потому что у них одна зп не зависимо от ранга, но у АШ большие деньги благодаря последним обновлениям, они получают долю с продажи с лицензий, а продают они их очень много. Если не хочешь платить налоги, устройся в мафию или же банду, там идёт зп с общака и гос-во туда не вмешивается, но задумайся... Гос. Налог не такой и большой, отсилу 1-2к, зато ты будешь состоять в гос. структуре, а это престиж. 
> И ещё,налоги может повышать Мэр, возможно он это и сделал, чтобы начала работать инфляция и так он пополняет казну штата
Думаю это и есть идеальное решение.

По поводу налога за дом:
А класс - 2% от гос. цены дома в месяц (Дома от 5.000.000 и выше)
В класс - 4% от гос. цены дома в месяц (Дома от 3.000.000 до 5.000.000)
С класс - 7% от гос. цены дома в месяц (Дома от 500.000 до 3.000.000)
D класс - 10% от гос. цены дома в месяц (Дома от 50.000 до 500.000)

Игроки должны оплачивать этот налог каждый месяц или заплатить сразу за пол.года - год (За оплату "экстерном" все налоги вырастают на 3%, это уберет тех людей которые оплатят и забьют на игру, дабы не занимать дома)

Все деньги с налогов идут в банк мэрии.

Источники налогов брал тут:
1. https://otvet.mail.ru/question/93914030
2. https://prian.ru/pub/2330.html

**Comment by alexpapay** [comment]
Реализацию оплаты авансом пока не пилил. Сложно пока представить как в наш сервак ее впилить. Налоги вычитаются при получении зп, дохода от биза. Процент может ставить мэр. **Нужен шмот для фракции мужской и женский.**
