### ISSUE TITLE
Карта v2.0

### ISSUE THREAD

**Issue by KoRRd93** [alexpapay/GTA5_reallife#30]
Семья - 4a9f05
Баллас - 8000d2
Марта - 0012ff

**Comment by KoRRd93** [comment]
![Uploading кв.png…]()

**Comment by alexpapay** [comment]
![image](https://cloud.githubusercontent.com/assets/18499853/26029487/6244ed14-3836-11e7-9951-d94661577763.png)

Вот такая карты получилась в итоге. 13х13 квадратов и пока от балды разместил стартовые неприкасаемые квадраты банд. Жду от вас номеров квадратов, где будут настоящие неприкасаемые места банд. А пока работаю над каптом.

**Comment by alexpapay** [comment]
Разместил равномерно по 30 квадратов каждой банды (Балласам досталось 29 кваратов - но зато каких))) В целом все отображается и работает. Центральным квадратам (которые нельзя каптить) сделал другой оттенок цвета банды.
