### ISSUE TITLE
координаты банд/бизнеса/фбр/больница

### ISSUE THREAD

**Issue by llxxxll4** [alexpapay/GTA5_reallife#31]
![4](https://cloud.githubusercontent.com/assets/19373764/26037318/6e108f22-38f9-11e7-8560-f3e98e00d2aa.png)
![default](https://cloud.githubusercontent.com/assets/19373764/26037319/6e11ac18-38f9-11e7-9a3e-aead627cf2e1.png)
![2](https://cloud.githubusercontent.com/assets/19373764/26037320/6e11bd7a-38f9-11e7-8047-e9f266be5fb6.png)
![2](https://cloud.githubusercontent.com/assets/19373764/26037322/6e12ceea-38f9-11e7-9034-7c4c5ce2e5b5.png)
![default](https://cloud.githubusercontent.com/assets/19373764/26037321/6e127d96-38f9-11e7-8903-1d3275c3bed8.png)
![default](https://cloud.githubusercontent.com/assets/19373764/26037323/6e13defc-38f9-11e7-8b82-8bddeacbead8.png)
![default](https://cloud.githubusercontent.com/assets/19373764/26037324/6e2814bc-38f9-11e7-847f-04c1b8510b85.png)
![3](https://cloud.githubusercontent.com/assets/19373764/26037325/6e2981d0-38f9-11e7-872d-e7dcb580bfc9.png)

Координаты мафии первой "-811.4462, 156.760788, 71.10809"

**Comment by alexpapay** [comment]
Не понял что должно быть в координате: 333 -1271 32. Все банды и так разместились по другим координатам успешно. 
Все остальное добавлено.

**Comment by llxxxll4** [comment]
Мы как запасные их взяли
