### ISSUE TITLE
Бизнесы

### ISSUE THREAD

**Issue by llxxxll4** [alexpapay/GTA5_reallife#32]
Давай пока на данный момент сделаем по бизнесам так

Устанавливаем руками цену бизнеса,а человеку,который купил биз раз в час будет падать 10к валюты за бизнес. Потом переделаем механизм,когда доделаем еще пару работ для реализации правильной работы биза.

**Comment by alexpapay** [comment]
Я сделал на заправках возможность снятия кассы (т.к. есть расход топлива и система по сути замкнулась, т.е. заправка теперь нужна всем, даже таксистам. И автобусам. Но добавил как ты и просил 10К капания за каждый из бизнесов.
