### ISSUE TITLE
Полиция

### ISSUE THREAD

**Issue by KoRRd93** [alexpapay/GTA5_reallife#37]
**ОСНОВНЫЕ ЗАДАЧИ ПОЛИЦИИ**

1.Борьба с преступностью.
2.Помощь в освоении новичкам путем РП ситуаций.
3.Участие в массовых РП мероприятиях.
4.Подготовка кандидатов к вступлению в ФБР.
5.Проведение различных рейдов для поддержания РП на сервере.

**Команды:**
Кадет - Офицер (1-2 ранг):
/r или /f - рация
/d - департамент
/tazer - смена вида пуль (резиновые/боевые бп)
/cuff [id] - надеть наручники
/uncuff [id] - снять наручники
/cput [id] - посадить человека в машину
/ceject [id] - высадить человека из машины
/follow [id] - пристегнуть задержанного к себе
/arrest [id] - посадить игрока в тюрьму
/mdc [id] - бортовой компьютер
/clear [id] - удалить розыск
/su [id] [Количество звёзд] [Причина] - выдать розыск
/ticket [id] [Сумма] [Причина] - выписать штраф
/frisk [id] - обыскать человека
/members - члены организации онлайн
/getekey - проверить количество ключей
/patrul - получить координаты преступника
/wanted - список разыскиваемых
/warehouse - кол-во материалов на складе
/takekeys [причина] - взять ключи для арестов

Мл. Сержант (3 ранг):
/givecopkeys [id] - выдать или забрать пропуск в здание ПД, Армию или ФБР

Сержант - Капитан (4-10 ранг):
/take [id] - Изъять что либо

Майор (11 ранг):
/giverank [id] [1-10 ранги] - повысить/понизить члена организации

Подполковник (12 ранг):
/uninvite [id] [Причина] - выгнать из организации

Полковник (13 ранг):
/iinvite [id] - принять человека в PD
/gov [Чат] - чат государственных новостей

Генерал-майор (14 ранг):
Все команды и повышение/понижение до 13 ранга

**Заработная плата офицеров ПД.**

Генерал-майор - 12.000$
Полковник - 11.000$
Подполковник - 10.500$
Майор - 10.000$
Капитан - 9.500$
Ст.Лейтенант - 9.000$
Лейтенант - 8.500$
Мл.Лейтенант - 8.000$
Ст.Прапорщик - 7.500$
Прапорщик - 7.000$
Сержант - 6.500$
Мл.Сержант - 6.000$
Офицер - 5.500$
Кадет - 5.000$

Техника полиции:
http://clip2net.com/s/3L2SVYA (Виды техники)

**(Нужно найти места для участков)**

**Comment by alexpapay** [comment]
Сделано практически все. Не сделанное будет написано в прогресс тикете. Все на меню рабочей профессии. Маты на маркере при создании оружия. Про тачки будет написано тоже в прогресс тикете.
