### ISSUE TITLE
МИНИСТЕРСТВО ЗДРАВООХРАНЕНИЯ

### ISSUE THREAD

**Issue by KoRRd93** [alexpapay/GTA5_reallife#38]
**ОСНОВНЫЕ ЗАДАЧИ М.З.**

1.Лечение игроков.
2.Помощь в освоении новичкам путем РП ситуаций.
3.Участие в массовых РП мероприятиях.
4.Лечение наркозависимости.
5.Проведение различных рейдов для поддержания РП на сервере.

Ранги и зарплаты:

Интерн [1 ранг] — 5000 тыс. вирт 
Санитар [2 ранг] — 5000 тыс. вирт 
Мед.Брат [3 ранг] — 5500 тыс. вирт 
Спасатель [4 ранг] — 6000 тыс. вирт 
Нарколог [5 ранг] — 6500 тыс. вирт 
Доктор [6 ранг] — 7000 тыс. вирт 
Психолог [7 ранг] — 7500 тыс. вирт 
Хирург [8 ранг] — 8000 тыс. вирт 
Зам.Глав.Врача [9 ранг] — 14000 тыс. вирт 
Глав.Врач [10 ранг] — 15000 тыс. вирт

КОМАНДЫ И ИХ ОПИСАНИЕ:

/heal [id] - Нужно находится в транспорте МЧС. Команда чтобы лечить, отрезвлять, снимать ломку 
/healaddict [id] - Лечить Наркозависимость (Нужно находится в больнице, один сеанс в час, всего 50 сеансов). Наркозависимость после 50 сеансов уменьшается до 2000 .
/r /f - Общий чат фракции.
/d - Рация департамента (доступна всем гос.фракциям).
/members - Список сотрудников онлайн.
/invite - Принять во фракцию (9 ранг).
/uninvite - Уволить игрока из фракции (8+ ранг).
/giverank - Повысить\понизить игрока(7+ранг).
/service - База данных с вызовами.
/sethealcost [цена] - Поставить цену лечения за 1 хп. (для лидера)
/spawnchange - Сменить подфракцию

Примечание!
Если нужно сделать сеанс пациенту, выполняем следующие действия:
- Сначала убираем ломку /heal id
- Далее делаем сам сеанс - /healaddict (Если не снять ломку, сеанс на засчитают)
Каждый сотрудник фракции может сменить себе пофдракцию.
Медики теперь могут лечить в машинах Stratum.
Только лидер фракции может повысить на руководящую должность (7+ ранг).
Если вас принимают в данную организацию, то после /invitе, ваша первоначальная подфракция - San-Fierro Medical Canter.

(Я так понял идет одна фракция МЗ, а "подфракция" это уже все больницы, но БОСС там один)

**Comment by alexpapay** [comment]
Принятие во фракцию сделано. Смена рангов и прочее по уровня доступа тоже. Не понял кто лидер фракции - главврач или же кто то вообще надо всеми еще есть? Я пока сделал типа босса фракции. 11 ранг. Т.к. внизу написано, что в будущем будет несколько подфракций итп. Установку стоимости 1 ХП сделал в БД. Лечение сделано. Лечение нарко сделано. Остались списки (как и для всех фракций - он на конец когда все фракции будут готовы). Машины медиков расставлены. Остался инт и точки больниц на карте. Тикет закрываю.
