### ISSUE TITLE
News

### ISSUE THREAD

**Issue by KoRRd93** [alexpapay/GTA5_reallife#41]
Задачи:
1. Задача фракции подавать объявления игроков в общий чат. (Пример: Продам машину 207го года за 30.000 )
2. Проводить прямые эфиры/брать интервью (Было в письменной форме опять же в чате)
3. По возможности добавить музыкальное и аудио вещание
4. Составлять колонку новостей в газете для почтальонов (которую могут редактировать новости и видеть все игроки в газете) 

примечание:
Каждый игрок мог выбрать какую из 3х радиостанций слушать, но объявления об услугах/покупке/продажи он видел сразу со всех радиостанций (При выборе радио 1, ты не видел эфиры со станции 2 и 3 и наоборот) 

**Ранги:**

☆ Стажёр [1]
☆ Звукооператор [2]
☆ Репортёр [4]
☆ Ведущий [5]
☆ Редактор [6]
☆ Гл.редактор [7] 
☆Программный Директор [9]
☆Ген. Директор [10]

**Команды:**

» Команды для 1 рангов «

/n [1/2] Прямой эфир/Выйти из прямого эфира - эфиры системно может проводить любой работник радиостанции;
/n [5/6] Взять/Завершить интервью - доступно всем работникам радиостанции;
/n [7] Объявления - команда, позволяющая попасть в меню объявлений редакции;
/n [8] Банк - увидеть банк новостей;
/f [текст] - РП-рация радиостанции;
/ratingnews - показать рейтинги радиостанций штата. Доступна для всех;
/members - команда, показывающая сотрудников, которые сейчас онлайн;
/newsbank - узнать банк радиостанции. Работает только в банке и у банкомата. Аналогично - /n [8] Банк

» Команды для 3 рангов «

/givenewskeys - выдать пропуск в студию.

» Команды для 5 рангов «

/n [3/4] Начать/Завершить принимать звонки - звонки на номер студии.

» Команды для 7 рангов «

/giverank [id] - повысить/понизить сотрудника (с 1го по 6й ранг)

» Команды для 8 рангов «

/giverank [id] - повысить/понизить сотрудника.
/uninvite [id] - уволить сотрудника.
/n - [9] Раздел лидера - установка цены символа объявлений и цены звонков/смс.

» Команды для 9 рангов «
/giverank [id] - повысить/понизить сотрудника.
/uninvite [id] - уволить сотрудника.
/invite [id] - принять человека на работу.
/n - [9] Раздел лидера - установка цены символа объявлений и цены звонков/смс.

» Команды для 10 рангов «
/n [9] Раздел лидера - установка зарплаты сотрудников, а также снятие денежных средств с банка новостей.
/offmembers - увидеть список сотрудников оффлайн.

» Основные сокращения «

к - тысяча вирт, тыс.вирт, тыс.в., т.в. (от лат.слова "кило" - "тысяча")
кк - миллион вирт, млн.вирт., м.в.
нарко - стиральный порошок, мука.
ганы - водяные пистолеты, железные игрушки.
маты - конструктор, детали конструктора.
форма - спец.одежда.
проценты машины (процы) - год выпуска, г.в.
мафия - охранное агентство, ЧОП (частное охранное предприятие).
банда - проф.баскетбольная команда, БК (баскетбольный клуб).
скиллы - навык владения оружием.
id - номер пейджера.
lvl (лвл) - года проживания в штате.
форум - оф.сайт.
набор - прием.
РМ - Русские Мишки.
Яки - Самураи.
LCN/ЛКН - Легионеры.

» Прямой эфир «

Для того, что бы выйти в прямой эфир нужно находиться в офисе или в фургоне редакции.
/n » [1] Прямой эфир
/n » [3] Начать принимать звонки/смс

» В начале эфира вы должны поприветствовать слушателя и представиться. Пример:
••• Музыкальная Заставка Los Santos News •••
Доброго времени суток. жители штата, с вами Arman Makarovskiy

Вся полезная информация и пример меню с САМП есть тут http://samp-rp.su/viewtopic.php?f=128&t=1953022

**Comment by alexpapay** [comment]
В принципе сделано многое, но не понятна механика некоторых функций, а также надо помещение и локацию для расположения фракции, чтобы выдавание пропусков на студию имело смысл. Илья, нужна твоя помощь в описании механик (я жирным ниже написал вопросы).

» Команды для 10 рангов «
/n [9] Раздел лидера - установка зарплаты сотрудников, а также снятие денежных средств с банка новостей. 
Я это сделал, но как то интересно - у других фракций не было еще такого. Чтобы лидеры ставили ставки на каждого. А будет еще где то?

**НЕ СДЕЛАНО:**
» Команды для 1 рангов «
/n [5/6] Взять/Завершить интервью - доступно всем работникам радиостанции; (**А как это работает? Приходит приглашение на интервью и потом с особой командой пишут оба игрока? Или как?**).
/n [7] Объявления - команда, позволяющая попасть в меню объявлений редакции; 
/n [8] Банк - увидеть банк новостей; (**А что это за банк? Можно немного подробнее? Это деньги фракции?**)
/f [текст] - РП-рация радиостанции;
/ratingnews - показать рейтинги радиостанций штата. Доступна для всех; (**Я так понял у нас пока станция одна - так что неактуально**)
/newsbank - узнать банк радиостанции. Работает только в банке и у банкомата. Аналогично - /n [8] Банк (**А это и есть деньги фракции?**)

» Команды для 5 рангов «
/n [3/4] Начать/Завершить принимать звонки - звонки на номер студии. (**Это вместе с телефоном будет как голос донастроят. Или делать еще и текстовую реализацию. Тогда дублируется с интервью выходит?**)

/offmembers - увидеть список сотрудников оффлайн. НОВОСТИ
/members - команда, показывающая сотрудников, которые сейчас онлайн;

**Comment by KoRRd93** [comment]
1. 

> /n [5/6] Взять/Завершить интервью - доступно всем работникам радиостанции; (А как это работает? Приходит приглашение на интервью и потом с особой командой пишут оба игрока? Или как?).

После ввода данной команды, выводились все сообщения которые игроки писали в обычный чат находясь рядом друг с другом. (Того кто брал интервью и давал его). Исключение сообщения которые вводились с командой (/r , /d , /b и т.п.) 

2. 

> /n [8] Банк - увидеть банк новостей; (А что это за банк? Можно немного подробнее? Это деньги фракции?)

Именно, админы штрафуют новости за подачу неправильных объявлений или другие нарушения, списывая деньги с этого банка. Директор новостей, так-же может выдавать разные плюшки сотрудникам с этих денег. Ну или себе оставлять.

3. 

> /newsbank - узнать банк радиостанции. Работает только в банке и у банкомата. Аналогично - /n [8] Банк (А это и есть деньги фракции?)

Я так понял это тоже самое что и 2.

4. 

> /n [3/4] Начать/Завершить принимать звонки - звонки на номер студии. (Это вместе с телефоном будет как голос донастроят. Или делать еще и текстовую реализацию. Тогда дублируется с интервью выходит?)

Это все было в текстовом формате, если есть возможность сделать 2 варианта, то будет круто. Не совсем то что интервью, тут они обычно проводят денежный конкурс (Например сколько будет 2+2=?) И тот кто первый успел дозвониться отвечает ну и получает приз или сливается и ждут нового звонка (Типо теле-шоу разных)
Но система вывода сообщений как в интервью только можно находиться далеко друг от друга.

**Comment by alexpapay** [comment]
Тикет закрываю. Все сделано. По голосовым звонкам - надо подрубить парня, который делает голос и спросить как делать директ звонки через его код.
