### ISSUE TITLE
Работа автомеханик

### ISSUE THREAD

**Issue by llxxxll4** [alexpapay/GTA5_reallife#43]
145.28636200, -140.37645000, 69.16806790   координаты,там разместим автомеханика.

Илья распиши работу

**Comment by KoRRd93** [comment]
Работа автомеханика одна из средних. Зарплата полностью зависит от того как будешь работать. Чем больше починишь, тем больше получишь, чем больше заправишь, аналогично. Правда с заправкой немного проблемы, надо ездить на заправку и заправляться.

Механик закупает бензин на заправке (По цене заправки), дальше он сам устанавливает цену на бензин и может продавать его за любую сумму.

С ремонтом так-же только ему ничего для этого не надо, цену на ремонт он ставит свою.

Доход:
От 0 до бесконечности 

Команды:
/fill [ID игрока] [Количество литров] [Цена]
/repair [ID игрока] [Цена]
/getfuel залить бензин (Надо быть у заправки)

(!) Внимание, вы покупаете бензин за тоже самую цену что и обычные игроки, далее уже сами делаете наценку.

**Comment by alexpapay** [comment]
Начал пилить и по описанию ни фига не понял как будет это работать?
Маркер механика стоит на точке - ок. Он как будет продавать бензин? Он будет храниться в маркере и игроки должны наехать на авто на маркер и выкупить бенз? Также цену он выставляет каждый раз разную (тогда тут взаимодействие с пользователем)? Или сколько будет стоить при наезде на маркер. Сам автомеханик должен быть на месте или маркер работает без него?
Как осуществляется доставка на маркер бензина? Обязательно на авто? Тогда он сливает с бака или везет отдельно (вводить доп переменную для этого в какой то из таблиц). 

В примере даны команды, но что такое айди игрока? проверять какие на его айди имеются машины? А если их несколько? Поэтому вижу вариант наезда на маркер игроками и починки с маркера. Он проще, но есть вопросы выше.

**Comment by alexpapay** [comment]
Сделано. Протестил на покупку топлива на заправке в маты. Все норм. Для остального - нужен тест с двумя игроками. Тикет закрываю. Отпишу щас в прогресс лист.
