### ISSUE TITLE
Для Ильи

### ISSUE THREAD

**Issue by llxxxll4** [alexpapay/GTA5_reallife#44]
Найти все заправки на карте
Найти магазины вещей
Найти место для таксопарка 

_______________________________
Анимации Леха скажет,как из гта тянуть их

**Comment by alexpapay** [comment]
По анимациям.

Вот список анимаций: https://wiki.gt-mp.net/index.php?title=Animations

Я ввел команду для теста анимаций. Пример: /animtest 1 mp_basejump	base_jump_spot
Копировать можете сразу и вставлять из списка оба параметра. Чтобы не вводить.

Как решите набрать анимаций - напишите в скайп, я залью обнову на сервак. 

И жду тогда списка анимаций, чтобы впилить это все в меню игрока для работы без команды.

**Comment by alexpapay** [comment]
Все сделано. Про анимации написал Илье - надо подбирать (впишешь в тикет Надо добавить). Этот тикет закрою, чтобы видеть что осталось, а то слишком много флуда в гите.
